auth-service:
    tty: true
    command:
    - "-l"
    - "debug"
    - "-t"
    - "console"
    - "run"
    - "--db-host"
    - "db"
    - "-p"
    - "9000"
    image: crackmac/go-auth:${auth_version}
    stdin_open: true
    links:
    - mysql-master:db

auth-lb:
  ports:
  - '9000:9000'
  - '9001:9001'
  labels:
    io.rancher.loadbalancer.ssl.ports: '9001'
    io.rancher.loadbalancer.target.auth-service: 9000=9000,9001=9000
  tty: true
  image: rancher/load-balancer-service
  links:
  - auth-service:auth-service
  stdin_open: true

mysql-master:
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: messenger
    MYSQL_USER: messenger
    MYSQL_PASSWORD: messenger
  expose:
    - "3306"
  tty: true
  image: mysql
  stdin_open: true
